Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BooksCatalogueMVC.Models
{
    public class Book
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public bool InStock { get; set; }

        public Category Category { get; set; }
    }
}

Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BooksCatalogueMVC.Models;
using BooksCatalogueMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BooksCatalogueMVC.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository bookRepository;
        private readonly ICategoryRepository categoryRepository;

        public BookController(IBookRepository bookrepo,ICategoryRepository categoryrepo)
        {
            bookRepository = bookrepo;
            categoryRepository = categoryrepo;
        }

        public IActionResult BookList()
        {
            BookListVM bookListVM = new BookListVM
            {
                Books = bookRepository.GetAllBooks,
                BookCategoryName = categoryRepository.GetAllCategories.ToList()[0].Name
            };

            return View(bookListVM);
        }

        public IActionResult BookDetails(int id)
        {
            Book book = bookRepository.GetBookById(id);
            return View(book);
        }
    }
}

Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BooksCatalogueMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace BooksCatalogueMVC.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IBookRepository bookRepository;
        private readonly ShoppingCart shoppingCart;

        public ShoppingCartController(IBookRepository bookRepo, ShoppingCart cart)
        {
            bookRepository = bookRepo;
            shoppingCart = cart;
        }
        public IActionResult Index()
        {
            shoppingCart.ShoppingCartItems = shoppingCart.GetShoppingCartItems();
            return View(shoppingCart);
        }

        public IActionResult AddToShoppingCart(int bookId)
        {
            Book book = bookRepository.GetBookById(bookId);
            shoppingCart.AddItemToCart(book,book.Price);
            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromShoppingCart(int bookId)
        {
            Book book = bookRepository.GetBookById(bookId);
            shoppingCart.RemoveItemFromCart(book);
            return RedirectToAction("Index");
        }
    }
}

Views/Book/BookDetails.cshtml
@model Book

<div class="card mb-3">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="@Model.ImageUrl" class="card-img" alt="@Model.Title">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h2 class="card-title">@Model.Title</h2>
                <p class="card-text">
                    <small class="text-muted">@Model.Author</small>
                </p>
                <p class="card-text">@Model.Category.Name</p>
                <p class="card-text">@Model.Price</p>
                <a asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-bookId=@Model.BookId 
                   class="btn btn-primary">Add To Cart</a>
            </div>
        </div>
    </div>
</div>

Views/Book/BookList.cshtml
@model BookListVM


<h1>@Model.BookCategoryName</h1>
<hr />
@foreach (var book in Model.Books)
{
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="@book.ImageUrl" alt="@book.Title">
        <div class="card-body">
            <h5 class="card-title">@book.Title</h5>
            <h6 class="card-subtitle">@book.Author</h6>
            <p class="card-text">@book.Category.Name</p> @*Can add book price here*@
            <a asp-controller="Book" asp-action="BookDetails" asp-route-id="@book.BookId"
               class="btn btn-primary">Details</a>
            <a asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-bookId=@book.BookId
               class="btn btn-primary">Add To Cart</a>
        </div>
    </div>
}